package Tests_Linux

import Tests_Linux.buildTypes.*
import Tests_Linux.vcsRoots.*
import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project

object Project : Project({
    id("Tests_Linux")
    name = "Tests (Linux)"

    vcsRoot(AtomicfuForAggregateVCS)
    vcsRoot(benchmarkForAggregateVCS)
    vcsRoot(JpsBuildTool)

    buildType(TestReproducibleMavenAgentVsDocker)
    buildType(TestReproducibleMavenDockerVsAgentAndCaches)
    buildType(AndroidCodegenTests_LINUX)
    buildType(ParcelizeTests_LINUX)
    buildType(JSCompilerTestsFIR_LINUX)
    buildType(JSCompilerTests_LINUX)
    buildType(CheckBuildTest_LINUX)
    buildType(ArtifactsTests)
    buildType(CodebaseTests)
    buildType(GradleIntegrationTestsMPPAndroidNative_LINUX)
    buildType(KAPTCompilerTests_LINUX)
    buildType(GradleIntegrationTestsGradleandKotlindaemonsKGPtests_LINUX)
    buildType(CodegenTestsOnJDK11_LINUX)
    buildType(JSCompilerTestsIR_LINUX)
    buildType(TestReproducibleDeployMavenVsDocker)
    buildType(CompilerTests21JDK)
    buildType(GradleIntegrationTestsAndroidKGPtests_LINUX)
    buildType(GradleIntegrationTestsMPPAndroidNativewithLatestGradle_LINUX)
    buildType(JSCompilerTestsFIRES6_LINUX)
    buildType(SerializationCompilationCheckK2)
    buildType(JVMCompilerTests_LINUX)
    buildType(GradleIntegrationTestsGradleKotlinMPPtests_LINUX)
    buildType(SerializationCompilationCheckK1)
    buildType(StatisticsPluginTests)
    buildType(FIRCompilerTests_LINUX)
    buildType(CodegenTestsOnJDK17_LINUX)
    buildType(kotlinxcoroutines)
    buildType(MiscCompilerTests_LINUX)
    buildType(FIR_LINUX)
    buildType(JSCompilerTestsIRES6_LINUX)
    buildType(ComposeTests)
    buildType(kotlinxAtomicfu)
    buildType(JPS_Tests)
    buildType(BootstrapTestFir_LINUX)
    buildType(GradleIntegrationTestsOtherGradleKotlintests_LINUX)
    buildType(GradleIntegrationTestsGradleKotlinnativetests_LINUX)
    buildType(GradleIntegrationTestsJVM_LINUX)
    buildType(FIRCompilerNightlyTests_LINUX)
    buildType(kotlinxAtomicfuK2Aggregate)
    buildType(BootstrapTest_LINUX)
    buildType(WASMCompilerTests_LINUX)
    buildType(TestReproducibleCompilerDockerVsAgent)
    buildType(BenchmarkCompilationCheckK1)
    buildType(BenchmarkCompilationCheckK2)
    buildType(JPSBuildTest_LINUX)
    buildType(FrontendApiTests_LINUX)
    buildType(WASMCompilerTestsK2_LINUX)
    buildType(GenerateTests_LINUX)
    buildType(GradleIntegrationTestsGradleKotlinJStests_LINUX)
})
